version: "3.2"

services:
  selenium:
    build: 
      context: ./app/
      dockerfile: Dockerfile-implementation
      # dockerfile: Dockerfile
    container_name: scraper
    network_mode: 'host'
    # ports:
    #   - 4000:4000
    privileged: true
    environment: 
      - CLIENTEMAIL=grant007r@gmail.com
      - CLIENTNAME=pladcloud